repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/gdubicki/pre-commit-pngquant
    rev: 9010345cf034fe1097b3b7bb9ecd5ea92dcf85dc
    hooks:
      - id: pngquant
        args: [--speed=1]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies: [ "@commitlint/config-conventional" ]
        args: [ "--extends", "@commitlint/config-conventional" ]
