language: python

python:
- '3.5'
- pypy

install: python setup.py develop

deploy:
  provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: python-egnyte
  password:
    secure: A3t0NzcInhf1JWDZyqxQRosfFg2odS0tlHsAIS5NdMZsPTD8UiilIEVvKkYtBToO1why6kOhUXAOLrFmBXkvTOcYdK9h8SBlcqi8e4jqJ6uenPfRuIRdRUWtj7iMpqt7UkbGV6r05MXmDqNPhguoMPRuH71l7/mKPSkaG5cN0jBoV7RdBpx1J4JJ8BOKUN9JvyIOZOZlAeMZGRLzgmnMZA5lw/2NoLL7Pbu9OYeox1e/Jc39xy6dTew0D/DWFM1H+Cm5DGq2sAeRD1sLnnzIyRT4KE7miUPi940BicvTL2QHjPDWIh1/P+Xn9gJwrmmgsLkzx8KS7zYE1jLV0QZQhRWqUx62n1TxbDcit+RWf7pjQwov4Iti3Q/0llzzkmerqzMak+Ci+S4HH98o7KBdbfJkSS8crW6AZO9qJKX6AlE4QXhH2aftxCOk33PiwCI9+0ubWwt8aMedbeQ3K75TR/J8+XdSaI0vGZuZ5QdCzxtnEf1O0SfRFFF2NmMX/gf325EWH4/YWX4xNy+Jib6AV2/xif5+xpE5mxWRqqgbBRskMGuN/nUuy6xnbV3EW9+UGnbhHtUZH7YPiMFPkyPlEU7C03arYINh6bpn46jb6j2W/o3+6E1BlzgvUCSI4betjlSaHw39pAir215TLpexPxCiNLT6ZmCHa27doGedNrU=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
