language: python

python:
- '3.5'

install: python setup.py develop

script: true

# test pypi
#deploy:
#  provider: pypi
#  distributions: sdist
#  server: https://test.pypi.org/legacy/
#  user: python-egnyte
#  password:
#    secure: A3t0NzcInhf1JWDZyqxQRosfFg2odS0tlHsAIS5NdMZsPTD8UiilIEVvKkYtBToO1why6kOhUXAOLrFmBXkvTOcYdK9h8SBlcqi8e4jqJ6uenPfRuIRdRUWtj7iMpqt7UkbGV6r05MXmDqNPhguoMPRuH71l7/mKPSkaG5cN0jBoV7RdBpx1J4JJ8BOKUN9JvyIOZOZlAeMZGRLzgmnMZA5lw/2NoLL7Pbu9OYeox1e/Jc39xy6dTew0D/DWFM1H+Cm5DGq2sAeRD1sLnnzIyRT4KE7miUPi940BicvTL2QHjPDWIh1/P+Xn9gJwrmmgsLkzx8KS7zYE1jLV0QZQhRWqUx62n1TxbDcit+RWf7pjQwov4Iti3Q/0llzzkmerqzMak+Ci+S4HH98o7KBdbfJkSS8crW6AZO9qJKX6AlE4QXhH2aftxCOk33PiwCI9+0ubWwt8aMedbeQ3K75TR/J8+XdSaI0vGZuZ5QdCzxtnEf1O0SfRFFF2NmMX/gf325EWH4/YWX4xNy+Jib6AV2/xif5+xpE5mxWRqqgbBRskMGuN/nUuy6xnbV3EW9+UGnbhHtUZH7YPiMFPkyPlEU7C03arYINh6bpn46jb6j2W/o3+6E1BlzgvUCSI4betjlSaHw39pAir215TLpexPxCiNLT6ZmCHa27doGedNrU=

deploy:
  provider: pypi
  user: python-egnyte
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  password:
    secure: "mvxlqAmq7Py5XBI3PEaJT71LmE1uGQZuqCIBxuXcBQLUVb+oJvsLYdK2OxSN3ty7AZvbYACh6PKbqwlmRRqpjvOtR2mpmLHap0i1cq9kSYwMqpuwv22dxY+ehe86+gKX2ENQdswp1zmiYmaoZjEAj+rti2ejiJTb8CsBxK65qA12qQUe5ZzhXc+bUjIw6q267DfvfWSbBKnFL4b66YNRRN2am5P0mRKGyNzUQKCKcqU4nUErU4Ge3vtSoNHz78w4I67hZeSZBKCu3y7fYHRt1V6UFx77NehNwzTfo0jUssieQ+8/9jr0/+Stuk45IaWnxfzTCrEJ1qOOuZF614ffBQtG1UE2YUfwAjpn1YOJ0dvnVi7NaTg4lUp+iI+n1psKqHYXkt8EV0zNLcqO0A49SLtId7qLiuaHHRjDxHeaWbTySp9mZ4xBGXSsF3VQVLLU5eqbT/malDm1TmK7G/HoKbIgqoA4z6lCNX2iaDKtrZuTKa/RyvLJTahTQrbWbDLTitRl+iaoo5nF2Q3MCh+MitOAoK8FKBsT7YWupV9N2CWCbvahNTCRBZTOOg146m3C0bedCzepxXtywl2PTibiVqD6LPEQ2Lez1Sm3OozufmxSFEzZahv9hVd5VxIiSuN/9PuLdO7YlpqFzDNzTehnprpbfksH+znfiJtUMJ2cyDk="
  on:
    tags: true
