name: Tests (integration)

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          pip install pypandoc pytest
          python setup.py develop
      - name: Run integration tests
        env:
          GITLAB_EE_LICENSE: ${{ secrets.GITLAB_EE_LICENSE }}
        run: |
          mv dev/* .
          ./run_gitlab_in_docker_ci.sh
          export GITLAB_URL=$(cat gitlab_url.txt)
          export GITLAB_TOKEN=$(cat gitlab_token.txt)
          py.test gitlabform/gitlabform/test
