---
name: Publish üê≥ to DockerHub

on:
  workflow_run:
    workflows: ["Linter and tests"]
    types:
      - completed

env:
  alpine_version: alpine3.12
  debian_version: buster

jobs:
  build-n-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' and startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [alpine, debian]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install packaging
      - name: Publish to DockerHub
        env:
          os: ${{ matrix.os }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          release_type=$(dev/check_release_type.py)
          export release_type
          ./dev/build_docker_images.sh
