---
name: Publish ðŸ³ to DockerHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install packaging
      - name: Get the version from the tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Wait for PyPI release
        run: |
          pip download gitlabform==${{ env.VERSION }} > /dev/null
          while [ $? -ne 0 ]; do sleep 10; pip3 download gitlabform==${{ env.VERSION }} > /dev/null ; done
        shell: bash {0}
      - name: Docker meta for Alpine-based image
        id: meta-alpine
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/gitlabform/gitlabform
            egnyte/gitlabform
          # Alpine-based images is the main one, so only it gets the 'latest' tag for public releases
          flavor: |
            latest=auto
          # Alpine-based images is the main one, so only it gets the non-suffixed tags
          tags: |
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=pep440,pattern={{version}}-alpine3.14
            type=pep440,pattern={{major}}.{{minor}}-alpine3.14
            type=pep440,pattern={{major}}-alpine3.14
      - name: Docker meta for Debian-based image
        id: meta-debian
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/gitlabform/gitlabform
            egnyte/gitlabform
          flavor: |
            latest=false
          tags: |
            type=pep440,pattern={{version}}-buster
            type=pep440,pattern={{major}}.{{minor}}-buster
            type=pep440,pattern={{major}}-buster
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # the legacy egnyte/gitlabform image lands here
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # gitlabform/gitlabform image is going to be here
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # This token is provided by Actions, you do not need to create your own token
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Debian-based image to registries
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./dev/debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-debian.outputs.tags }}
          labels: ${{ steps.meta-debian.outputs.labels }}
      - name: Publish Alpine-based image to registries
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./dev/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
