name: Tests Ultimate

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true

jobs:
  acceptance-tests-ultimate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.12, 3.14]
      fail-fast : false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install wheel
          pip install -e .[test]
      - name: Start GitLab in Docker (OPTIONAL)
        continue-on-error: true # Ultimate License via link only lasts for 90days so may need renewing, don't block other PRs
        env:
          # requested via: https://handbook.gitlab.com/handbook/marketing/developer-relations/contributor-success/community-contributors-workflows/#contributing-to-the-gitlab-enterprise-edition-ee
          # https://gitlab.com/gitlab-org/developer-relations/contributor-success/team-task/-/issues
          GITLAB_EE_LICENSE: ${{ secrets.GITLAB_EE_ULTIMATE_LICENSE }}
        run: ./dev/run_gitlab_in_docker.sh
      - name: Run acceptance tests that require Ultimate license (OPTIONAL)
        continue-on-error: true # Ultimate License via link only lasts for 90days so may need renewing, don't block other PRs
        run: pytest --durations=0 --reruns 3 --reruns-delay 10 tests/acceptance/ultimate
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3
        continue-on-error: true # Ultimate License via link only lasts for 90days so may need renewing, don't block other PRs
        with:
          action: codecov/codecov-action@v3
          with: |
            name: codecov-acceptance-test-ultimate
            flags: integration
            token: 3e6d6cb5-fcdb-41ea-b134-f6c5856363e9
          attempt_limit: 5
          attempt_delay: 10000